export const CHAINCODE_NAME = 'mychannel'
export const CHANNEL_NAME = 'BuySell'
export const LENOVO_URL = 'https://lbstest.mybluemix.net/'
export const ODM_URL = 'https://odmtest.mybluemix.net/'
export const SUPPLIER_URL = 'https://suptest.mybluemix.net/'
