export const CHAINCODE_NAME = 'BuySell'
export const CHANNEL_NAME = 'BuySell'
export const LENOVO_URL = 'https://lenovobs.mybluemix.net/'
export const ODM_URL = 'https://odm1bs.mybluemix.net/'
export const SUPPLIER_URL = 'https://supplier1bs.mybluemix.net/'
